### ISSUE TITLE
Meta naming

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_serialize#4]
Currently I implemented `@:tink.encode` and `@:tink.decode` on type level which is counterpart of `@:jsonStringify` and `@:jsonParse` respectively (can change if needed, I only used it for testing).

As for field level (`@:json`), how about just `@:tink.serialize`?

**Comment by back2dos** [comment]
> As for field level (`@:json`)

For what purpose? The serialization format doesn't contain field names ^^

**Comment by kevinresol** [comment]
Would be nice if it can be used to specify the order of anon fields or index of enum ctors so that it won't break when new fields/ctors are added in the middle.

**Comment by back2dos** [comment]
Hmm. Yeah, change resilience is definitely an issue.

- For enums, we can add a define/meta that uses constructor names instead of indices (I wanted to add string caching anyway, so this wouldn't really impact size).
- For fields, this won't do, because of how tightly objects are packed - there's not even a terminator. Once the value of the last field is written/read, the object is done. So if the encoder and decoder assume different amounts of fields, everything breaks spectacularly. We could allow tagging object types as "dynamic" or as "schema based", to allow for differences between type information on both ends.

**Comment by kevinresol** [comment]
alright :wink:
